name: Build System Tool

on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v4

    - name: 配置 MSVC 开发者命令提示符
      uses: ilammy/msvc-dev-cmd@v1

    - name: 使用 CMake 配置并编译
      run: |
        cmake -B build
        cmake --build build --config Release
      
    - name: 上传可执行文件产物
      uses: actions/upload-artifact@v4
      with:
        name: SysRunner-Release
        path: build/Release/SysRunner.exe
        retention-days: 7
